### ISSUE TITLE
[CRASH] magma staff 

### ISSUE THREAD

**Issue by witheredpathogen** [opekope2/StaffMod#46]
### Loader and its version

latest one that is not a snapshot

### Staff Mod version

latest one currently

### Steps to reproduce

I was just messing around in a village with the staff, i burned down a tree and when i got too close and the fireballs disappeared, when i turned to look at something else it crashed, not sure if this is exactly what happened.

### Game logs

Couldn't get them :(

**Comment by opekope2** [comment]
https://minecraft.wiki/w/Tutorials/Obtaining_a_crash_report
Search for `avm_staff` in it

**Comment by opekope2** [comment]
Idk how I messed it up, only the magma block is affected.
Don't shoot fireballs if you're looking at a wall closer than about 2 blocks until I fix it.
